// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrQUNglCehGKskHXhSMw7oGXVUYz_bOdc',
    appId: '1:386213891296:web:2619608e45faee6c1d9485',
    messagingSenderId: '386213891296',
    projectId: 'careerconnect-8b7e7',
    authDomain: 'careerconnect-8b7e7.firebaseapp.com',
    storageBucket: 'careerconnect-8b7e7.appspot.com',
    measurementId: 'G-H94BJ8P5DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlJHjI9na0bbL1WB2inZZ5AhZcxsWyVeU',
    appId: '1:386213891296:android:eb6f334ec19211e41d9485',
    messagingSenderId: '386213891296',
    projectId: 'careerconnect-8b7e7',
    storageBucket: 'careerconnect-8b7e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTPM2bp9rWJrmxSuL0u04jDAtt_2ZsGk',
    appId: '1:386213891296:ios:22b3d59738d41b5a1d9485',
    messagingSenderId: '386213891296',
    projectId: 'careerconnect-8b7e7',
    storageBucket: 'careerconnect-8b7e7.appspot.com',
    iosBundleId: 'com.example.careerconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTPM2bp9rWJrmxSuL0u04jDAtt_2ZsGk',
    appId: '1:386213891296:ios:22b3d59738d41b5a1d9485',
    messagingSenderId: '386213891296',
    projectId: 'careerconnect-8b7e7',
    storageBucket: 'careerconnect-8b7e7.appspot.com',
    iosBundleId: 'com.example.careerconnect',
  );

}